#!/bin/sh
# Archives old track logs on a Garmin GPS's microSD card,
# then backs up archived logs and POIs to the local drive
# -- Parameters --
GPSVOLUME="/mnt/usb"
BACKUPDIR="$HOME/docs/GPSBackup"
# ----------------

# Get log files except todays
THEDATE=`date +%Y%m%d`
for file in `ls $GPSVOLUME/*.gpx | grep -v $THEDATE`
do
	echo $file
	# Move them into the TrackLogs folder
	mv "$file" "$GPSVOLUME/TrackLogs/"
done

# Now back things up
rsync -a "$GPSVOLUME/TrackLogs" "$BACKUPDIR"
rsync -a "$GPSVOLUME/Garmin/POI" "$BACKUPDIR"
