#!/bin/sh
# Archives old track logs on a Garmin GPS's microSD card,
# then backs up archived logs and POIs to the local drive
# -- Parameters --
GPSVOLUME="VISTAHCX"
BACKUPDIR="$HOME/Documents/GPSBackup"
# ----------------

# Get log files except todays
THEDATE=`date +%Y%m%d`
for file in `ls /Volumes/$GPSVOLUME/*.gpx | grep -v $THEDATE`
do
	echo $file
	# Move them into the TrackLogs folder
	mv "$file" "/Volumes/$GPSVOLUME/TrackLogs/"
done

# Now back things up
rsync -a "/Volumes/$GPSVOLUME/TrackLogs" "$BACKUPDIR"
rsync -a "/Volumes/$GPSVOLUME/Garmin/POI" "$BACKUPDIR"
