#!/usr/bin/perl
# Usage: $0 lightbox_page images_dir out_dir

use warnings;
use strict;
use autodie;
use File::Copy;

if ($#ARGV + 1 != 3) {
	die "3 arguments must be provided";
}

my ($in_page, $src_dir, $out_dir) = @ARGV;

open IN_PAGE, $in_page;
open PIC_DESC, ">$out_dir/pic-desc.txt";
open PIC_SORT, ">$out_dir/pic-sort.txt";
print PIC_DESC "; Do not remove this comment (used for UTF-8 compliance)\n\n";
print PIC_SORT "; Do not remove this comment (used for UTF-8 compliance)\n\n";

while (<IN_PAGE>) {
	# Get image names and captions
	if (/images\/(.*?\.(?:jpg|png|gif)).*?title="(.*?)"/) {
		# Copy image
		copy ("$src_dir/$1", $out_dir);
		# Write to pic-desc and pic-sort
		print PIC_DESC "$1 | $2\n";
		print PIC_SORT "$1\n";
	}	
}
close IN_PAGE;

# Create thumbnail directory
mkdir "$out_dir/thumbnails";

# Create blank index.html
open FH, ">$out_dir/index.html";
close FH;

# Create gal-desc.txt
open FH, ">$out_dir/gal-desc.txt";
close FH;
