#!/bin/sh
PRIVATE="$HOME/Private"
TMPDIR="$PRIVATE/tmp"
TESTFILE="$TMPDIR"

MOUNT="ecryptfs-mount-private"
UMOUNT="ecryptfs-umount-private"
NOTIFY="notify-send"

if [ ! -t 0 ]; then MOUNT="xterm -e '$MOUNT'"; fi

while [ ! -e "$TESTFILE" ]; do $UMOUNT; $MOUNT; done # sometimes doesn't work
if [ ! -z "$NOTIFY" ]; then $NOTIFY "$PRIVATE mounted"; fi

if [ ! -d "$TMPDIR" ]; then mkdir $TMPDIR; fi
export TMPDIR

$@

$UMOUNT
if [ ! -z "$NOTIFY" ]; then $NOTIFY "$PRIVATE unmounted"; fi

